analytics: {}
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.75
  saturation: 0.75
cta: {}
layout_spectrum: 0.844594
name: Alex Georgiou
opengraph: {}
purpose: []
typography_spectrum: 0.65613
