name: Alex Georgiou
favicon: null
layout_spectrum: 0.85285
typography_spectrum: 0.65613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76224021-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
