name: Alex Georgiou
favicon: null
layout_spectrum: 0.86355
typography_spectrum: 0.65613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76224021-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e54118'
    - '#000000'
    - '#fdf8f1'
    - '#b9b9ba'
    - '#3a3c3b'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
