name: Alex Georgiou
favicon: null
layout_spectrum: 0.40095
typography_spectrum: 0.67528
title: The Book - Alex Georgiou
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76224021-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e54118'
    - '#000000'
    - '#fdf8f1'
    - '#b9b9ba'
    - '#3a3c3b'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
