name: Alex Georgiou
favicon: null
layout_spectrum: 0.83936
typography_spectrum: 0.67528
title: The Book - Alex Georgiou
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76224021-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#080000'
    - '#fcbd1a'
    - '#f03d00'
    - '#ac0000'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
